"""subscriptions

Revision ID: 0040ddd26729
Revises: 
Create Date: 2022-12-08 23:55:21.686566

"""
import uuid

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from azure_sql.models import Subscription

# revision identifiers, used by Alembic.
revision = '0040ddd26729'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Subscriptions',
                    sa.Column('subscription_id', postgresql.UUID(as_uuid=True), nullable=False),
                    sa.Column('display_name', sa.String(), nullable=True),
                    sa.Column('enabled', sa.Boolean(), nullable=True),
                    sa.PrimaryKeyConstraint('subscription_id')
                    )
    # ### end Alembic commands ###
    seed()


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Subscriptions')
    # ### end Alembic commands ###


def seed():
    i = 0
    op.bulk_insert(
        Subscription.__table__,
        [
            {"subscription_id": uuid.uuid4(), "display_name": f"Subscription {(i := i + 1)}", "enabled": True},
            {"subscription_id": uuid.uuid4(), "display_name": f"Subscription {(i := i + 1)}", "enabled": True},
        ],
    )
